# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'URLImage'
  # Pods for TMDB
  target 'TMDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDBUITests' do
    # Pods for testing
  end

end
